# Generated by Django 4.0.6 on 2022-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='img_url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
