# Generated by Django 4.0.6 on 2022-07-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_apps', '0002_watchlist_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
